client_max_body_size 20M;

server {
    listen 80;
    index index.html;
    root /var/www/public/;
    server_name _;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /static {
       alias /var/www/public/static/;
       add_header Cache-Control "public, immutable, max-age=31536000";
    }
}

{{ if .Env.BACKEND_SERVER_NAME }}
server {
    listen 80;
    server_name {{ .Env.BACKEND_SERVER_NAME }};

    location / {
        set $backend_url http://{{ .Env.URL_BACKEND }};
        proxy_pass $backend_url;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
}
{{ end }}
