client_max_body_size 20M;

server {
    listen 80;
    index index.html;
    root /var/www/public/;
    server_name _;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /static {
       alias /var/www/public/static/;
       add_header Cache-Control "public, immutable, max-age=31536000";
    }
}
